FROM mcr.microsoft.com/windows/nanoserver:1809

# One

ARG MODE
RUN Echo %MODE%

# Two

# ENV MODE=Release
# ARG MODE

# RUN Echo %MODE%

# Three

# ARG MODE
# ENV MODE=%MODE%

# RUN Echo %MODE%